version: '3.8'
services:
#  app:
#    image: hackaton-grupo32:0.0.1-SNAPSHOT
#    ports:
#      - 8080:8080
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/timemgm
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=postgres
#    depends_on:
#      - db
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres