application:
  name: hackaton-grupo32

##PostgreSQL
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/timemgm}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:create-drop}
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
  docker:
    compose:
      enabled: false
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
            required: 'true'
          auth: 'true'
    host: sandbox.smtp.mailtrap.io
    username: 70f9987ed14c9e
    password: 0900641cb2bdf2
    port: '587'

security:
  jwt:
    public-key: classpath:app.pub
    private-key: classpath:app.key
