application:
  name: hackaton-grupo32

##PostgreSQL
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/timemgm
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
  docker:
    compose:
      enabled: false

security:
  jwt:
    public-key: classpath:app.pub
    private-key: classpath:app.key